name: Build workflow
run-name: Build workflow
on:
  workflow_dispatch:
  push:
    branches:
    - master
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    container:
      image: perldocker/perl-tester:${{ matrix.perl-version }}
    strategy:
      matrix:
        perl-version:
        - '5.24'
        - '5.26'
        - '5.28'
        - '5.30'
        - '5.32'
        - '5.34'
    steps:
    - uses: actions/checkout@v4
    - name: pre_install
      run: |
        cpm install --no-test \
        --mirror=http://cpan.cpantesters.org/ Test::Requires::Git Devel::Cover::Report::Coveralls

    - name: Install dist deps
      run: cpanm -n --installdeps .
    - name: Run Tests
      run: perl Makefile.PL && make build && make test
    - name: after_sucess
      run: cover -test -report coveralls
